<?php
return ['content-type'=>'text/plain; charset=UTF-8','plural-forms'=>'nplurals=2; plural=(n > 1);','language'=>'fr_FR','language-team'=>'French (France)','po-revision-date'=>'2025-08-08 09:20+0000','x-generator'=>'Loco https://localise.biz/','messages'=>['Actions'=>'Actions','Already sent'=>'Déjà envoyé','Basic'=>'Basique','Basic settings'=>'Paramètres de base','Button text (Default: Leave review)'=>'Texte du bouton (Par défaut : Laisser un avis)','Create a message that will be sent'=>'Créer un message qui sera envoyé','Customization'=>'Personnalisation','Debug'=>'Débogage','Debug Settings'=>'Paramètres de débogage','Desktop CSS'=>'CSS pour ordinateur de bureau

','E-mail'=>'E-mail','Email configurations'=>'Configurations e-mail','Email header'=>'En-tête de l\'e-mail','Email subject'=>'Objet de l\'e-mail','Email text'=>'Texte de l\'e-mail','Enable log to order note'=>'Activer le journal dans la note de commande','Enter email...'=>'Saisir l\'e-mail...','Enter header...'=>'Saisir l\'en-tête...','Enter text...'=>'Entrez le texte...','Enter the css...'=>'Entrez le CSS...

','Enter the email...'=>'Saisir l\'e-mail...','Enter the sender...'=>'Saisir l\'expéditeur...','Enter the subject...'=>'Saisir l\'objet...','Global'=>'Global','https://morkva.co.ua/product-category/plugins/'=>'https://morkva.co.ua/product-category/plugins/','Leave review'=>'Laisser un avis','Mobile CSS'=>'CSS pour mobile

','MORKVA'=>'MORKVA','Morkva Review Reminder'=>'Rappel d\'avis Morkva','Morkva Review Reminder PRO'=>'Morkva Review Reminder PRO','MRKV Review Reminder'=>'Rappel d\'avis MRKV','Need help or customisation?'=>'Besoin d\'aide ou de personnalisation ?','Order status filter'=>'Filtre de statut de commande

','Plain only css'=>'CSS simple uniquement','Plain text, no html'=>'Texte brut, pas de HTML','Product categories'=>'Catégories de produits

','Reminder interval, days'=>'Intervalle de rappel, jours','Remove reminder'=>'Supprimer le rappel','Reply-to (separated by comma)'=>'Répondre à (séparés par une virgule)','Resend reminder'=>'Renvoyer le rappel','Review recently purchased products'=>'Évaluer les produits récemment achetés','Review Reminder'=>'Rappel d\'avis','Save'=>'Enregistrer','Scheduled on:'=>'Programmé le :','Send'=>'Envoyer','Send a test email to the specified email. The product will be taken the last one published'=>'Envoyer un e-mail de test à l\'adresse e-mail spécifiée. Le produit sera le dernier publié','Send now'=>'Envoyer maintenant','Sender name'=>'Nom de l\'expéditeur','Sent'=>'Envoyé','Settings'=>'Paramètres','Shortcode firstname: [mrkv-firstname]'=>'Code court prénom : [mrkv-firstname]','Support'=>'Assistance','Test Email address'=>'Adresse e-mail de test','Test letter'=>'Lettre de test','View details'=>'Voir les détails','We send simple emails to remind you of your review'=>'Nous envoyons des e-mails simples pour vous rappeler de laisser un avis','When selected, only orders with choosen statuses will be processed'=>'Lorsqu\'il est sélectionné, seuls les commandes avec les statuts choisis seront traitées

','When selected, only orders with related categories products will be processed'=>'Lorsque cette option est sélectionnée, seules les commandes contenant des produits des catégories concernées seront traitées']];
