<?php
return ['content-type'=>'text/plain; charset=UTF-8','plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'bg_BG','language-team'=>'Bulgarian','po-revision-date'=>'2025-07-31 06:17+0000','x-generator'=>'Loco https://localise.biz/','messages'=>['Actions'=>'Действия','Already sent'=>'Вече изпратено','Basic'=>'Основни','Basic settings'=>'Основни настройки','Button text (Default: Leave review)'=>'Текст на бутона (по подразбиране: Оставете отзив)','Create a message that will be sent'=>'Създайте съобщение, което ще бъде изпратено','Customization'=>'Персонализиране

','Debug'=>'Отстраняване на грешки','Debug Settings'=>'Настройки за отстраняване на грешки','Desktop CSS'=>'CSS за десктоп

','E-mail'=>'Имейл','Email configurations'=>'Имейл конфигурации','Email header'=>'Заглавка на имейл','Email subject'=>'Тема на имейл','Email text'=>'Текст на имейл','Enable log to order note'=>'Включване на дневник към бележка за поръчка','Enter email...'=>'Въведете имейл...','Enter header...'=>'Въведете заглавка...','Enter text...'=>'Въведете текст...','Enter the css...'=>'Въведете CSS...

','Enter the email...'=>'Въведете имейл...','Enter the sender...'=>'Въведете подателя...','Enter the subject...'=>'Въведете темата...','Global'=>'Глобални','https://morkva.co.ua/product-category/plugins/'=>'https://morkva.co.ua/product-category/plugins/','Leave review'=>'Оставете отзив','Mobile CSS'=>'CSS за мобилни устройства

','MORKVA'=>'MORKVA','Morkva Review Reminder'=>'Morkva Напомняне за преглед','Morkva Review Reminder PRO'=>'Morkva Review Reminder PRO','MRKV Review Reminder'=>'MRKV Напомняне за преглед','Need help or customisation?'=>'Нуждаете се от помощ или персонализация?','Plain only css'=>'Само обикновен CSS','Plain text, no html'=>'Обикновен текст, без HTML','Product categories'=>'Категории продукти','Reminder interval, days'=>'Интервал за напомняне, дни','Remove reminder'=>'Премахване на напомняне','Reply-to (separated by comma)'=>'Отговор до (разделени със запетая)','Resend reminder'=>'Изпрати напомняне отново','Review recently purchased products'=>'Прегледайте наскоро закупените продукти','Review Reminder'=>'Напомняне за преглед','Save'=>'Запазване','Scheduled on:'=>'Планирано за:','Send'=>'Изпрати','Send a test email to the specified email. The product will be taken the last one published'=>'Изпратете тестов имейл на посочения адрес. Продуктът ще бъде последният публикуван','Send now'=>'Изпрати сега','Sender name'=>'Име на подател','Sent'=>'Изпратено','Settings'=>'Настройки','Shortcode firstname: [mrkv-firstname]'=>'Кратък код за първо име: [mrkv-firstname]','Support'=>'Поддръжка','Test Email address'=>'Тестов имейл адрес','Test letter'=>'Тестово писмо','View details'=>'Виж подробности','We send simple emails to remind you of your review'=>'Изпращаме ви обикновени имейли, за да ви напомним за вашето ревю','When selected, only orders with related categories products will be processed'=>'Когато е избрано, ще се обработват само поръчки с продукти от съответните категории']];
